# Generated by Django 4.2.5 on 2023-10-04 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me_name', models.CharField(max_length=150, null=True)),
                ('med_image', models.ImageField(null=True, upload_to='media/')),
                ('med_desc', models.CharField(max_length=1550, null=True)),
                ('med_price', models.CharField(max_length=50, null=True)),
                ('med_totalquantity', models.CharField(max_length=50, null=True)),
                ('med_directionforuse', models.CharField(max_length=550, null=True)),
                ('med_sideeffects', models.CharField(max_length=550, null=True)),
                ('med_warnings', models.CharField(max_length=550, null=True)),
                ('med_consumetype', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
