# Generated by Django 4.2.5 on 2023-10-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='me_name',
            new_name='med_name',
        ),
    ]
