# Generated by Django 4.2.5 on 2023-10-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalApp', '0002_rename_me_name_medicine_med_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharma_name', models.CharField(max_length=200, null=True)),
                ('pharma_location', models.CharField(max_length=200, null=True)),
                ('pharma_phone', models.CharField(max_length=200, null=True)),
                ('pharma_email', models.EmailField(max_length=200, null=True)),
                ('pharma_image', models.ImageField(null=True, upload_to='media/')),
                ('password', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
