# Generated by Django 4.2.5 on 2023-10-12 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalApp', '0007_rename_name_addtocart_med_name_addtocart_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='public_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalApp.signup'),
        ),
    ]
