# Generated by Django 4.2.5 on 2023-10-25 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalApp', '0010_assign_delete_pharmacy_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='pharmacy_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalApp.pharmacy'),
        ),
        migrations.AddField(
            model_name='assign',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalApp.medicine'),
        ),
        migrations.AddField(
            model_name='assign',
            name='price',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='assign',
            name='quantity',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
